name = "classlog"
pages_build_output_dir = "."

[vars]
GOOGLE_CLIENT_ID = "PASTE-YOUR-CLIENT-ID-HERE.apps.googleusercontent.com"

[[kv_namespaces]]
binding = "LOG_KV"
id = "31f4f4749b914b66b60bef363e9dc74d"
