name = "classlog"
pages_build_output_dir = "."

[vars]
GOOGLE_CLIENT_ID = "1062864609603-255734b8pm6f23ej4nehjtqmcjrri5sq.apps.googleusercontent.com"

[[kv_namespaces]]
binding = "LOG_KV"
id = "31f4f4749b914b66b60bef363e9dc74d"
